### ISSUE TITLE
Remove the `internal_unstable` feature flag

### ISSUE THREAD

**Issue by uint** [near/near-account-id#1]
I couldn't find any convincing justification for not keeping [`AccountId::new_unvalidated`](https://github.com/near/near-account-id/blob/03b2ce6b86dad62c1a2ba4f9d4fdc1892ce2b214/src/lib.rs#L313) a part of the public API - though then again, I suspect this code was only used internally.

Meanwhile, having an "unchecked" constructor does have performance benefits. Minimizing the number of feature flags is also good practice.

I propose we remove the feature flag, rename `new_unvalidated` to `new_unchecked` (more idiomatic), keep the constructor public and let contract devs enjoy a choice.

The next release is likely going to be breaking anyway.

@frol

**Comment by frol** [comment]
This method was needed as a workaround for legacy reasons and we hoped we would never need to use it. We wanted to communicate that it is not wise to use this method, and `unsafe` is not right way to do that as there is no memory unsafety associated with it. At the same time, I think, it is up to the developers to decide what is good for them, so having an ugly name of `new_unchecked` might be enough to draw attention to the problem. I think I am less strict these days, and can see this to be part of the public API without hiding it behind a feature flag

**Comment by uint** [comment]
Closed by https://github.com/near/near-account-id/commit/8b70a85fe8182b163ef3aab0995cb17cb4ca6952
